# Generated by Django 4.2.5 on 2023-09-17 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=20)),
                ('mfd', models.DateField()),
                ('best_before', models.DurationField()),
                ('description', models.TextField()),
            ],
        ),
    ]
